services:
  laravel:
    image: webdevops/php-apache-dev:8.2
    container_name: laravel
    volumes:
      - ./laravel:/var/www
    ports:
      - 8003:80
      #- 443:443
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public/
    depends_on:
      - rabbitmq
      - db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  node:
    image: node:18-alpine
    volumes:
      - ./node:/app
    working_dir: /app
    command: sh -c "/usr/local/bin/npm i --prefix /app && /usr/local/bin/npm run dev --prefix /app"
    depends_on:
      - rabbitmq
  db:
    image: mysql:8
    platform: linux/x86_64
    restart: always
    command: --mysql-native-password=ON
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
